return {
	-- "olimorris/onedarkpro.nvim",
	-- priority = 1000, -- Ensure it loads first
	-- config = function()
	-- 	require("onedarkpro").setup({
	-- 		colors = {
	-- 			-- red = "#FF0000",
	-- 		},
	-- 		options = {
	-- 			cursorline = true,
	-- 			transparency = false,
	-- 		},
	-- 		highlights = {
	-- 			-- overide cursor line fill colors
	-- 			CursorLine = { bg = "#333842" },
	-- 			-- overide nvimtree folder icon fill color
	-- 			NvimTreeFolderIcon = { fg = "#6776a7" },
	-- 			-- overide nvimtree text fill color folder opened
	-- 			NvimTreeOpenedFolderName = { fg = "#6776a7" },
	-- 			-- overide nvimtree text fill color root folder
	-- 			NvimTreeRootFolder = { fg = "#6776a7" },
	-- 			-- overide cmp cursorline fill color with #333842
	-- 			PmenuSel = { bg = "#333842" },
	-- 			illuminatedWord = { bg = "#3b4261" },
	-- 			illuminatedCurWord = { bg = "#3b4261" },
	-- 			IlluminatedWordText = { bg = "#3b4261" },
	-- 			IlluminatedWordRead = { bg = "#3b4261" },
	-- 			IlluminatedWordWrite = { bg = "#3b4261" },
	-- 			StatusLine = { fg = "#f8f8f2", bg = "${bg}" },
	-- 			StatusLineTerm = { fg = "#f8f8f2", bg = "${bg}" },
	-- 			BufferLineFill = { bg = "${bg}" },
	-- 			Pmenu = { fg = "${fg}", bg = "${bg}" },
	-- 			-- overide lualine fill color with bg color
	-- 			LualineNormal = { bg = "${bg}" },
	-- 			-- overide lualine_c fill color with bg color
	-- 			LualineC = { bg = "${bg}" },
	-- 			-- overide lualine_x fill color with bg color
	-- 			LualineX = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKey = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKeySeperator = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKeyDesc = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKeyFloat = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKeyValue = { bg = "${bg}" },
	-- 			-- overide which-key fill color with bg color
	-- 			WhichKeyBorder = { bg = "${bg}" },
	-- 		},
	-- 	})
	-- end,
}
