local web_devicons_ok, web_devicons = pcall(require, "nvim-web-devicons")
if not web_devicons_ok then
	return
end

local material_icon_ok, material_icon = pcall(require, "nvim-material-icon")
if not material_icon_ok then
	return
end

material_icon.setup({
	override = {
		["mjs"] = {
			icon = "󰌞",
			color = "#f2c55c",
			cterm_color = "220",
			name = "Mjs",
		},
		["js"] = {
			icon = "󰌞",
			color = "#f2c55c",
			cterm_color = "220",
			name = "javascript",
		},
		["ts"] = {
			icon = "󰛦",
			color = "#548af7",
			cterm_color = "220",
			name = "ts",
		},
		["jsx"] = {
			icon = "",
			color = "#61dafb",
			cterm_color = "220",
			name = "jsx",
		},
		["tsx"] = {
			icon = "",
			color = "#3699ff",
			cterm_color = "220",
			name = "Tsx",
		},
		["svg"] = {
			icon = "󰜡",
			color = "#FDB03A",
			cterm_color = "220",
			name = "svg",
		},
		["prisma"] = {
			icon = "",
			color = "#0FBFCF",
			cterm_color = "220",
			name = "prisma",
		},
		["json"] = {
			icon = "",
			color = "#f16421",
			cterm_color = "220",
			name = "json",
		},
		["map"] = {
			icon = "",
			color = "#748e54",
			cterm_color = "220",
			name = "map",
		},
		["svelte"] = {
			icon = "",
			color = "#ef510b",
			cterm_color = "220",
			name = "svelte",
		},
		["yaml"] = {
			icon = "󰰳",
			color = "#ef510b",
			cterm_color = "220",
			name = "yaml",
		},
		["vsix"] = {
			icon = "",
			color = "#30A2FF",
			cterm_color = "220",
			name = "vsix",
		},
		["class"] = {
			icon = "󰅶",
			color = "#1e88e5",
			cterm_color = "220",
			name = "JavaClass",
		},
		["java"] = {
			icon = "󰅶",
			color = "#ef510b",
			cterm_color = "220",
			name = "JavaFile",
		},
		["gradle"] = {
			icon = "",
			color = "#9C9C9C",
			cterm_color = "220",
			name = "GradleFile",
		},
		["mod"] = {
			icon = "󰟓",
			color = "#C5362B",
			cterm_color = "220",
			name = "gomod",
		},
		["blade.php"] = {
			icon = "󰫐",
			color = "#ef510b",
			cterm_color = "220",
			name = "bladephp",
		},
		["7z"] = {
			icon = "",
			color = "#9C9C9C",
			cterm_color = "220",
			name = "7z",
		},
		["rar"] = {
			icon = "",
			color = "#9C9C9C",
			cterm_color = "220",
			name = "rar",
		},
		["cfm"] = {
			icon = "",
			color = "#507F89",
			cterm_color = "220",
			name = "cfm",
		},
		["cfc"] = {
			icon = "",
			color = "#507F89",
			cterm_color = "220",
			name = "cfc",
		},
		["png"] = {
			icon = "󰋩",
			color = "#3574f0",
			cterm_color = "220",
			name = "Png",
		},
		["jpg"] = {
			icon = "󰋩",
			color = "#3574f0",
			cterm_color = "220",
			name = "jpg",
		},
		["jpeg"] = {
			icon = "󰥶",
			color = "#88C057",
			cterm_color = "220",
			name = "jpeg",
		},
		["csv"] = {
			icon = "󰈚",
			color = "#57965c",
			cterm_color = "220",
			name = "csv",
		},
		["sql"] = {
			icon = "󰆼",
			color = "#b589ec",
			cterm_color = "220",
			name = "sqlfile",
		},
		["php"] = {
			icon = "󰌟",
			color = "#b589ec",
			cterm_color = "220",
			name = "phpfile",
		},
		["mp4"] = {
			icon = "󰈫",
			color = "#FC6411",
			cterm_color = "220",
			name = "mp4file",
		},
		["md"] = {
			icon = "",
			color = "#42a5f5",
			cterm_color = "220",
			name = "Md",
		},
		["sh"] = {
			icon = "",
			color = "#ef510b",
			cterm_color = "220",
			name = "README_file",
		},
		["pdf"] = {
			icon = "",
			color = "#ef510b",
			cterm_color = "220",
			name = "pdffile",
		},
		["xlsx"] = {
			icon = "󱀭",
			color = "#349C42",
			cterm_color = "220",
			name = "xlsxfile",
		},
		["xls"] = {
			icon = "󱀭",
			color = "#349C42",
			cterm_color = "220",
			name = "xlsfile",
		},
		["py"] = {
			icon = "󰌠",
			color = "#387EB8",
			cterm_color = "220",
			name = "pythonfile",
		},
		["vue"] = {
			icon = "󰡄",
			color = "#4dba87",
			cterm_color = "220",
			name = "vuefile",
		},
		["xml"] = {
			icon = "󰗀",
			color = "#f1662a",
			cterm_color = "220",
			name = "xmlfile",
		},
		["yml"] = {
			icon = "󰰳",
			color = "#fbc02d",
			cterm_color = "220",
			name = "Ymlfile",
		},
		["txt"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "220",
			name = "txtfile",
		},
		["toml"] = {
			icon = "",
			color = "#9c4221",
			cterm_color = "124",
			name = "Toml",
		},
		-- ["go"] = {
		-- 	icon = "󰟓",
		-- 	color = "#0FBFCF",
		-- 	cterm_color = "220",
		-- 	name = "go",
		-- },
		[".babelrc"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Babelrc",
		},
		[".bash_profile"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "BashProfile",
		},
		[".bashrc"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Bashrc",
		},
		[".DS_Store"] = {
			icon = "",
			color = "#41535b",
			cterm_color = "239",
			name = "DsStore",
		},
		[".gitconfig"] = {
			icon = "",
			color = "#41535b",
			cterm_color = "239",
			name = "GitConfig",
		},
		[".gitlab-ci.yml"] = {
			icon = "",
			color = "#e24329",
			cterm_color = "166",
			name = "GitlabCI",
		},
		[".gvimrc"] = {
			icon = "",
			color = "#019833",
			cterm_color = "29",
			name = "Gvimrc",
		},
		[".npmignore"] = {
			icon = "",
			color = "#E8274B",
			cterm_color = "161",
			name = "NPMIgnore",
		},
		[".npmrc"] = {
			icon = "",
			color = "#E8274B",
			cterm_color = "161",
			name = "NPMrc",
		},
		[".settings.json"] = {
			icon = "",
			color = "#854CC7",
			cterm_color = "98",
			name = "SettingsJson",
		},
		[".vimrc"] = {
			icon = "",
			color = "#019833",
			cterm_color = "29",
			name = "Vimrc",
		},
		[".zprofile"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Zshprofile",
		},
		[".zshenv"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Zshenv",
		},
		[".zshrc"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Zshrc",
		},
		["Brewfile"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Brewfile",
		},
		["CMakeLists.txt"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "CMakeLists",
		},
		["COPYING"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "License",
		},
		["COPYING.LESSER"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "License",
		},
		["Dockerfile"] = {
			icon = "",
			color = "#0087c9",
			cterm_color = "32",
			name = "Dockerfile",
		},
		["Gemfile$"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Gemfile",
		},
		["Rmd"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Rmd",
		},
		["Vagrantfile$"] = {
			icon = "",
			color = "#1563FF",
			cterm_color = "27",
			name = "Vagrantfile",
		},
		["_gvimrc"] = {
			icon = "",
			color = "#019833",
			cterm_color = "29",
			name = "Gvimrc",
		},
		["_vimrc"] = {
			icon = "",
			color = "#019833",
			cterm_color = "29",
			name = "Vimrc",
		},
		["ai"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Ai",
		},
		["awk"] = {
			icon = "",
			color = "#4d5a5e",
			cterm_color = "240",
			name = "Awk",
		},
		["bash"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Bash",
		},
		["bat"] = {
			icon = "",
			color = "#C1F12E",
			cterm_color = "154",
			name = "Bat",
		},
		["c"] = {
			icon = "",
			color = "#599eff",
			cterm_color = "75",
			name = "C",
		},
		["c++"] = {
			icon = "",
			color = "#f34b7d",
			cterm_color = "204",
			name = "CPlusPlus",
		},
		["cbl"] = {
			icon = "⚙",
			color = "#005ca5",
			cterm_color = "25",
			name = "Cobol",
		},
		["cc"] = {
			icon = "",
			color = "#f34b7d",
			cterm_color = "204",
			name = "CPlusPlus",
		},
		["cfg"] = {
			icon = "",
			color = "#ECECEC",
			cterm_color = "255",
			name = "Configuration",
		},
		["clj"] = {
			icon = "",
			color = "#8dc149",
			cterm_color = "107",
			name = "Clojure",
		},
		["cljc"] = {
			icon = "",
			color = "#8dc149",
			cterm_color = "107",
			name = "ClojureC",
		},
		["cljs"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "ClojureJS",
		},
		["cljd"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "ClojureDart",
		},
		["cmake"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "CMake",
		},
		["cob"] = {
			icon = "⚙",
			color = "#005ca5",
			cterm_color = "25",
			name = "Cobol",
		},
		["cobol"] = {
			icon = "⚙",
			color = "#005ca5",
			cterm_color = "25",
			name = "Cobol",
		},
		["coffee"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Coffee",
		},
		["conf"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "Conf",
		},
		["config.ru"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "ConfigRu",
		},
		["cp"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Cp",
		},
		["cpp"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Cpp",
		},
		["cpy"] = {
			icon = "⚙",
			color = "#005ca5",
			cterm_color = "25",
			name = "Cobol",
		},
		["cr"] = {
			icon = "",
			color = "#000000",
			cterm_color = "16",
			name = "Crystal",
		},
		["csh"] = {
			icon = "",
			color = "#4d5a5e",
			cterm_color = "240",
			name = "Csh",
		},
		["cson"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Cson",
		},
		["css"] = {
			icon = "",
			color = "#42a5f5",
			cterm_color = "75",
			name = "Css",
		},
		["cxx"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Cxx",
		},
		["d"] = {
			icon = "",
			color = "#427819",
			cterm_color = "64",
			name = "D",
		},
		["dart"] = {
			icon = "",
			color = "#03589C",
			cterm_color = "25",
			name = "Dart",
		},
		["db"] = {
			icon = "",
			color = "#dad8d8",
			cterm_color = "253",
			name = "Db",
		},
		["desktop"] = {
			icon = "",
			color = "#563d7c",
			cterm_color = "60",
			name = "DesktopEntry",
		},
		["diff"] = {
			icon = "",
			color = "#41535b",
			cterm_color = "239",
			name = "Diff",
		},
		["dockerfile"] = {
			icon = "",
			color = "#0087c9",
			cterm_color = "32",
			name = "Dockerfile",
		},
		["drl"] = {
			icon = "",
			color = "#ffafaf",
			cterm_color = "217",
			name = "Drools",
		},
		["dropbox"] = {
			icon = "",
			color = "#0061FE",
			cterm_color = "27",
			name = "Dropbox",
		},
		["dump"] = {
			icon = "",
			color = "#dad8d8",
			cterm_color = "253",
			name = "Dump",
		},
		["edn"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Edn",
		},
		["eex"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Eex",
		},
		["ejs"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Ejs",
		},
		["elm"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Elm",
		},
		["epp"] = {
			icon = "",
			color = "#FFA61A",
			cterm_color = "214",
			name = "Epp",
		},
		["erb"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Erb",
		},
		["erl"] = {
			icon = "",
			color = "#B83998",
			cterm_color = "132",
			name = "Erl",
		},
		["ex"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Ex",
		},
		["exs"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Exs",
		},
		["f#"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Fsharp",
		},
		["favicon.ico"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Favicon",
		},
		["fnl"] = {
			icon = "",
			color = "#fff3d7",
			cterm_color = "230",
			name = "Fennel",
		},
		["fs"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Fs",
		},
		["fsi"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Fsi",
		},
		["fsscript"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Fsscript",
		},
		["fsx"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Fsx",
		},
		["gd"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "GDScript",
		},
		["gemspec"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Gemspec",
		},
		["gif"] = {
			icon = "",
			color = "#26a69a",
			cterm_color = "36",
			name = "Gif",
		},
		["glb"] = {
			icon = "",
			color = "#FFB13B",
			cterm_color = "215",
			name = "BinaryGLTF",
		},
		["go"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Go",
		},
		["godot"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "GodotProject",
		},
		["graphql"] = {
			icon = "",
			color = "#e535ab",
			cterm_color = "169",
			name = "GraphQL",
		},
		["gruntfile"] = {
			icon = "",
			color = "#e37933",
			cterm_color = "173",
			name = "Gruntfile",
		},
		["gulpfile"] = {
			icon = "",
			color = "#cc3e44",
			cterm_color = "167",
			name = "Gulpfile",
		},
		["h"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "H",
		},
		["haml"] = {
			icon = "",
			color = "#eaeae1",
			cterm_color = "254",
			name = "Haml",
		},
		["hbs"] = {
			icon = "",
			color = "#f0772b",
			cterm_color = "208",
			name = "Hbs",
		},
		["heex"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Heex",
		},
		["hh"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Hh",
		},
		["hpp"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Hpp",
		},
		["hrl"] = {
			icon = "",
			color = "#B83998",
			cterm_color = "132",
			name = "Hrl",
		},
		["hs"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Hs",
		},
		["htm"] = {
			icon = "",
			color = "#e34c26",
			cterm_color = "166",
			name = "Htm",
		},
		["html"] = {
			icon = "",
			color = "#e44d26",
			cterm_color = "166",
			name = "Html",
		},
		["hxx"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Hxx",
		},
		["ico"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Ico",
		},
		["import"] = {
			icon = "",
			color = "#ECECEC",
			cterm_color = "255",
			name = "ImportConfiguration",
		},
		["ini"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "Ini",
		},
		["jl"] = {
			icon = "",
			color = "#a270ba",
			cterm_color = "133",
			name = "Jl",
		},
		["json5"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "Json5",
		},
		["ksh"] = {
			icon = "",
			color = "#4d5a5e",
			cterm_color = "240",
			name = "Ksh",
		},
		["kt"] = {
			icon = "",
			color = "#F88A02",
			cterm_color = "208",
			name = "Kotlin",
		},
		["kts"] = {
			icon = "",
			color = "#F88A02",
			cterm_color = "208",
			name = "KotlinScript",
		},
		["leex"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Leex",
		},
		["less"] = {
			icon = "",
			color = "#563d7c",
			cterm_color = "60",
			name = "Less",
		},
		["lhs"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Lhs",
		},
		["lua"] = {
			icon = "",
			color = "#51a0cf",
			cterm_color = "74",
			name = "Lua",
		},
		["luau"] = {
			icon = "",
			color = "#51a0cf",
			cterm_color = "74",
			name = "Luau",
		},
		["makefile"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "Makefile",
		},
		["markdown"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Markdown",
		},
		["mdx"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Mdx",
		},
		["mix.lock"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "MixLock",
		},
		["ml"] = {
			icon = "λ",
			color = "#e37933",
			cterm_color = "173",
			name = "Ml",
		},
		["mli"] = {
			icon = "λ",
			color = "#e37933",
			cterm_color = "173",
			name = "Mli",
		},
		["mo"] = {
			icon = "∞",
			color = "#9772FB",
			cterm_color = "99",
			name = "Motoko",
		},
		["mustache"] = {
			icon = "",
			color = "#e37933",
			cterm_color = "173",
			name = "Mustache",
		},
		["nim"] = {
			icon = "",
			color = "#f3d400",
			cterm_color = "220",
			name = "Nim",
		},
		["nix"] = {
			icon = "",
			color = "#7ebae4",
			cterm_color = "110",
			name = "Nix",
		},
		["otf"] = {
			icon = "",
			color = "#ECECEC",
			cterm_color = "255",
			name = "OpenTypeFont",
		},
		["pck"] = {
			icon = "",
			color = "#6d8086",
			cterm_color = "66",
			name = "PackedResource",
		},
		["pp"] = {
			icon = "",
			color = "#FFA61A",
			cterm_color = "214",
			name = "Pp",
		},
		["Procfile"] = {
			icon = "",
			color = "#a074c4",
			cterm_color = "140",
			name = "Procfile",
		},
		["ps1"] = {
			icon = "",
			color = "#4d5a5e",
			cterm_color = "240",
			name = "PromptPs1",
		},
		["psb"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Psb",
		},
		["psd"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Psd",
		},
		["query"] = {
			icon = "",
			color = "#90a850",
			cterm_color = "107",
			name = "Query",
		},
		["rake"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Rake",
		},
		["rakefile"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Rakefile",
		},
		["rb"] = {
			icon = "",
			color = "#701516",
			cterm_color = "1",
			name = "Rb",
		},
		["rlib"] = {
			icon = "",
			color = "#dea584",
			cterm_color = "180",
			name = "Rlib",
		},
		["rmd"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Rmd",
		},
		["rs"] = {
			icon = "",
			color = "#dea584",
			cterm_color = "180",
			name = "Rs",
		},
		["rss"] = {
			icon = "",
			color = "#FB9D3B",
			cterm_color = "215",
			name = "Rss",
		},
		["sass"] = {
			icon = "",
			color = "#f55385",
			cterm_color = "204",
			name = "Sass",
		},
		["sbt"] = {
			icon = "",
			color = "#cc3e44",
			cterm_color = "167",
			name = "sbt",
		},
		["scala"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "Scala",
		},
		["scm"] = {
			icon = "ﬦ",
			color = "#000000",
			cterm_color = "16",
			name = "Scheme",
		},
		["scss"] = {
			icon = "",
			color = "#f55385",
			cterm_color = "204",
			name = "Scss",
		},
		["sig"] = {
			icon = "λ",
			color = "#e37933",
			cterm_color = "173",
			name = "Sig",
		},
		["slim"] = {
			icon = "",
			color = "#e34c26",
			cterm_color = "166",
			name = "Slim",
		},
		["sln"] = {
			icon = "",
			color = "#854CC7",
			cterm_color = "98",
			name = "Sln",
		},
		["sml"] = {
			icon = "λ",
			color = "#e37933",
			cterm_color = "173",
			name = "Sml",
		},
		["sqlite"] = {
			icon = "",
			color = "#dad8d8",
			cterm_color = "253",
			name = "Sql",
		},
		["sqlite3"] = {
			icon = "",
			color = "#dad8d8",
			cterm_color = "253",
			name = "Sql",
		},
		["styl"] = {
			icon = "",
			color = "#8dc149",
			cterm_color = "107",
			name = "Styl",
		},
		["sublime"] = {
			icon = "",
			color = "#e37933",
			cterm_color = "173",
			name = "Suo",
		},
		["suo"] = {
			icon = "",
			color = "#854CC7",
			cterm_color = "98",
			name = "Suo",
		},
		["t"] = {
			icon = "",
			color = "#519aba",
			cterm_color = "67",
			name = "Tor",
		},
		["terminal"] = {
			icon = "",
			color = "#31B53E",
			cterm_color = "71",
			name = "Terminal",
		},
		["tres"] = {
			icon = "",
			color = "#cbcb41",
			cterm_color = "185",
			name = "TextResource",
		},
		["twig"] = {
			icon = "",
			color = "#8dc149",
			cterm_color = "107",
			name = "Twig",
		},
		["vim"] = {
			icon = "",
			color = "#019833",
			cterm_color = "29",
			name = "Vim",
		},
		["webmanifest"] = {
			icon = "",
			color = "#f1e05a",
			cterm_color = "221",
			name = "Webmanifest",
		},
		["xcplayground"] = {
			icon = "",
			color = "#e37933",
			cterm_color = "173",
			name = "XcPlayground",
		},
		["zig"] = {
			icon = "",
			color = "#f69a1b",
			cterm_color = "208",
			name = "Zig",
		},
		["zsh"] = {
			icon = "",
			color = "#89e051",
			cterm_color = "113",
			name = "Zsh",
		},
		[".env"] = {
			icon = "",
			color = "#faf743",
			cterm_color = "227",
			name = "Env",
		},
		["lock"] = {
			icon = "",
			color = "#ffd54f",
			cterm_color = "221",
			name = "Lock",
		},
		["log"] = {
			icon = "",
			color = "#ffffff",
			cterm_color = "231",
			name = "Log",
		},
		["zip"] = {
			icon = "",
			color = "#afb42b",
			cterm_color = "142",
			name = "Zip",
		},
		["xz"] = {
			icon = "",
			color = "#afb42b",
			cterm_color = "142",
			name = "Xz",
		},
		["test.js"] = {
			icon = "",
			color = "#ffca28",
			cterm_color = "220",
			name = "TestJavascript",
		},
		["test.jsx"] = {
			icon = "",
			color = "#00bcd4",
			cterm_color = "38",
			name = "TestJavascriptReact",
		},
		["test.ts"] = {
			icon = "",
			color = "#00bcd4",
			cterm_color = "38",
			name = "TestTypescript",
		},
		["ttf"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "Ttf",
		},
		["woff"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "WebOpenFontFormat",
		},
		["woff2"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "WebOpenFontFormat",
		},
		["hex"] = {
			icon = "",
			color = "#26a69a",
			cterm_color = "36",
			name = "Hex",
		},
		["bin"] = {
			icon = "",
			color = "#26a69a",
			cterm_color = "36",
			name = "Bin",
		},
		["dat"] = {
			icon = "",
			color = "#26a69a",
			cterm_color = "36",
			name = "Dat",
		},
		["abc"] = {
			icon = "",
			color = "#ff5722",
			cterm_color = "202",
			name = "Abc",
		},
		["babel.config.js"] = {
			icon = "",
			color = "#fdd835",
			cterm_color = "221",
			name = "BabelConfig",
		},
		["bf"] = {
			icon = "",
			color = "#ff4081",
			cterm_color = "204",
			name = "Bf",
		},
		["exe"] = {
			icon = "",
			color = "#e64a19",
			cterm_color = "166",
			name = "Exe",
		},
		["pptx"] = {
			icon = "",
			color = "#d14524",
			cterm_color = "166",
			name = "Pptx",
		},
		["obj"] = {
			icon = "",
			color = "#29b6f6",
			cterm_color = "39",
			name = "Obj",
		},
		["fbx"] = {
			icon = "",
			color = "#29b6f6",
			cterm_color = "39",
			name = "Fbx",
		},
		["deb"] = {
			icon = "",
			color = "#ff0283",
			cterm_color = "198",
			name = "Deb",
		},
		["rpm"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "Rpm",
		},
		["README.md"] = {
			icon = "",
			color = "#42a5f5",
			cterm_color = "75",
			name = "README.md",
		},
		["razor"] = {
			icon = "",
			color = "#42a5f5",
			cterm_color = "75",
			name = "razor",
		},
		["sc"] = {
			icon = "",
			color = "#f44336",
			cterm_color = "203",
			name = "sc",
		},
	},
	color_icons = true,
	default = true,
})

web_devicons.setup({
	override = material_icon.get_icons(),
	override_by_filename = {
		["artisan"] = {
			icon = "󰫐",
			color = "#ef510b",
			cterm_color = "240",
			name = "artisan",
		},
		["vite.config.ts"] = {
			icon = "󰉁",
			color = "#ffab00",
			cterm_color = "240",
			name = "viteconfigts",
		},
		["vite.config.js"] = {
			icon = "󰉁",
			color = "#ffab00",
			cterm_color = "240",
			name = "viteconfigjs",
		},
		[".releaserc"] = {
			icon = "󰚧",
			color = "#9C9C9C",
			cterm_color = "240",
			name = "releaserc",
		},
		[".profile"] = {
			icon = "󰙄",
			color = "#9C9C9C",
			cterm_color = "240",
			name = "profiledata",
		},
		[".eslint_d"] = {
			icon = "󰱺",
			color = "#4930bd",
			cterm_color = "240",
			name = "eslintd",
		},
		[".eslintrc.cjs"] = {
			icon = "󰱺",
			color = "#4930bd",
			cterm_color = "240",
			name = "eslintrccjs",
		},
		[".htaccess"] = {
			icon = "󰛓",
			color = "#C63C17",
			cterm_color = "240",
			name = "htaccess",
		},
		["pom.xml"] = {
			icon = "󰛓",
			color = "#C63C17",
			cterm_color = "240",
			name = "pomxml",
		},
		[".huskyrc"] = {
			icon = "󰩃",
			color = "#ffffff",
			cterm_color = "240",
			name = "huskyrc",
		},
		[".prettierrc"] = {
			icon = "",
			color = "#ea5e5e",
			cterm_color = "240",
			name = "prettierrc",
		},
		[".prettierrc.json"] = {
			icon = "",
			color = "#ea5e5e",
			cterm_color = "240",
			name = "prettierrcjson",
		},
		[".prettierd"] = {
			icon = "",
			color = "#ea5e5e",
			cterm_color = "240",
			name = "prettierd",
		},
		[".vscodeignore"] = {
			icon = "",
			color = "#30A2FF",
			cterm_color = "240",
			name = "vscodeignore",
		},
		[".vsixmanifest"] = {
			icon = "",
			color = "#30A2FF",
			cterm_color = "240",
			name = "vsixmanifest",
		},
		[".prettierignore"] = {
			icon = "",
			color = "#ea5e5e",
			cterm_color = "240",
			name = "prettierignore",
		},
		[".sequelizerc"] = {
			icon = "󱙌",
			color = "#397883",
			cterm_color = "220",
			name = "sequelizerc",
		},
		["pre-commit"] = {
			icon = "",
			color = "#75e4b3",
			cterm_color = "240",
			name = "pre",
		},
		["yarn.lock"] = {
			icon = "",
			color = "#ea5e5e",
			cterm_color = "240",
			name = "yarnlock",
		},
		["yarn-error.log"] = {
			icon = "",
			color = "#3d85c6",
			cterm_color = "240",
			name = "yarnerror",
		},
		[".eslintrc.json"] = {
			icon = "󰱺",
			color = "#4746a8",
			cterm_color = "240",
			name = "eslintrc",
		},
		[".eslintrc.js"] = {
			icon = "󰱺",
			color = "#4746a8",
			cterm_color = "240",
			name = "eslintrcjs",
		},
		[".eslintignore"] = {
			icon = "󰱺",
			color = "#4746a8",
			cterm_color = "240",
			name = "eslintignore",
		},
		["jest.config.js"] = {
			icon = "󰚐",
			color = "#e37575",
			cterm_color = "220",
			name = "jestconfig",
		},
		["cname"] = {
			icon = "󰖟",
			color = "#e37575",
			cterm_color = "220",
			name = "cname",
		},
		[".nvmrc"] = {
			icon = "",
			color = "#E8274B",
			cterm_color = "220",
			name = "nvmrc",
		},
		[".yarnrc"] = {
			icon = "",
			color = "#3d85c6",
			cterm_color = "240",
			name = "yarnrc",
		},
		[".git-blame-ignore-revs"] = {
			icon = "󰊢",
			color = "#F14C28",
			cterm_color = "220",
			name = "gitblameignorerevs",
		},
		[".gitmodules"] = {
			icon = "󰊢",
			color = "#0c343d",
			cterm_color = "220",
			name = "gitmodules",
		},
		[".mailmap"] = {
			icon = "󰇮",
			color = "#a0d0d0",
			cterm_color = "220",
			name = "mailmap",
		},
		[".vscode-test.js"] = {
			icon = "󰨞",
			color = "#206ba3",
			cterm_color = "220",
			name = "vscodetest",
		},
		[".mention-bot"] = {
			icon = "󰚩",
			color = "#ffffff",
			cterm_color = "220",
			name = "mentionbot",
		},
		[".project"] = {
			icon = "󰈚",
			color = "#5881b1",
			cterm_color = "220",
			name = "project",
		},
		["gradlew"] = {
			icon = "",
			color = "#9C9C9C",
			cterm_color = "220",
			name = "gradlewFile",
		},
		[".classpath"] = {
			icon = "󰅶",
			color = "#9C9C9C",
			cterm_color = "220",
			name = "gradlewFile",
		},
		["dockerfile-development"] = {
			icon = "",
			color = "#0087c9",
			cterm_color = "220",
			name = "gradlewFile-development",
		},
		["dockerfile-staging"] = {
			icon = "",
			color = "#0087c9",
			cterm_color = "220",
			name = "gradlewFile-staging",
		},
		["nodemon.json"] = {
			icon = "󰇴",
			color = "#76d04b",
			cterm_color = "220",
			name = "nodemonjson",
		},
		["webpack.config.js"] = {
			icon = "󰜫",
			color = "#8ED6FB",
			cterm_color = "220",
			name = "webpackconfigjs",
		},
		["package.json"] = {
			icon = "󰎙",
			color = "#8ED6FB",
			cterm_color = "220",
			name = "packagejson",
		},
		["package-lock.json"] = {
			icon = "󰎙",
			color = "#cc0000",
			cterm_color = "220",
			name = "packagelockjson",
		},
		[".gitignore"] = {
			icon = "󰊢",
			color = "#8ED6FB",
			cterm_color = "220",
			name = "gitignore",
		},
		["tsconfig.json"] = {
			icon = "󰛦",
			color = "#519aba",
			cterm_color = "74",
			name = "TSConfig",
		},
		["jsconfig.json"] = {
			icon = "󰌞",
			color = "#f2c55c",
			cterm_color = "220",
			name = "JSConfig",
		},
		[".gitlab-ci.yml"] = {
			icon = "",
			color = "#F14C28",
			cterm_color = "220",
			name = "gitlabciyaml",
		},
		[".env_example"] = {
			icon = "",
			color = "#faf743",
			cterm_color = "227",
			name = "Envexample",
		},
		["README.md"] = {
			icon = "󰋼",
			color = "#faf743",
			cterm_color = "227",
			name = "readmefile",
		},
	},
})
