require("config.lazy")
require("user.colorscheme")
require("user.keymaps")
-- require("user.options")
-- require("user.keymaps")
-- require("user.autocommands")
-- require("user.format_onsave")
-- require("user.snip")
-- require("user.bufferline")
-- require("user.chat_gpt")
-- vim.cmd("colorscheme onedark")
vim.cmd("colorscheme dracula")
