require("custom.default")
require("custom.dashboard")
require("config.lazy")
require("user.colorscheme")
require("user.keymaps")
-- require("user.snip")
require("core.neovide")
-- require("user.nvim-tree")
-- require("user.options")
-- require("user.keymaps")
-- require("user.autocommands")
-- require("user.format_onsave")
-- require("user.snip")
-- require("user.bufferline")
-- require("user.chat_gpt")
