require("config.lazy")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.format_onsave")
require("user.colorscheme")
-- require("user.snip")
-- require("user.bufferline")
-- require("user.chat_gpt")
